### ISSUE TITLE
Missing documentation for :actions value can also be lambda functions

### ISSUE THREAD

**Issue by tigersoldier** [magit/magit-popup#4]
The current documentation about the `:actions` values of `magit-define-popup` says it accepts either a string or a `(key desc command)` form. However it also accepts `((lambda () ...))` and use the evaluated result, which is not documented.

**Comment by tarsius** [comment]
There is some behavior that I implemented in a hackish way because I needed it soon, but which I did not document because of the hackish nature and because I intend to write a replacement for `magit-popup`, which does these things more gracefully.

I believe those are the commits that implemented these features, consult the commit messages for "documentation":

- Support using a function in place of constant variables list cc9f7d2abf65b0f7955f8633c815f5c0ca5e74bb
- Allow putting actions into variable sections b2c1ae7ee3ce2d82e1dd2d03dcc71f98ca6fddb1
- Support functions as descriptions of actions f05acee23bb9149acab10b959d3bb17df5a9ce9f
- Support functions as subsection headings 7a68cc853e52f56f5e2b3c8c694d1703c4c6d014

**Comment by tigersoldier** [comment]
Does that mean third-party packages shouldn't use those feature or they take risks of incompatible breakage in the future?

**Comment by tarsius** [comment]
No, you can use it. Breaking changes are of course always possible but rather unlikely by now.

I might get around to document this properly some time - consider this collection a first step toward that goal. Might take a while though. Looking at uses in Magit might also help using these features as intended.

**Comment by tigersoldier** [comment]
Thanks Jonas. This is very helpful and assuring.

**Comment by tarsius** [comment]
These features are now documented in the manual and the doc-string.
